image: docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build
  - test
  - deploy

before_script:
  - apk add -U py2-pip
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  - export COMPOSE_PROJECT_NAME=gitlab-$CI_JOB_ID

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:build-$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:build-$CI_COMMIT_REF_SLUG

test:
  stage: test
  script:
    - echo 'running tests...'
  coverage: '/All files[ |]+[0-9.]+[ |]+([0-9.]+)/'

deploy_dev:
  stage: deploy
  script:
    - echo 'deploying...'
  environment:
    name: dev
    url: https://sto-platform-issuer.dev.diginex.fun
  only:
    - master
